import { z } from "zod";
import {
  nonNegativeIntegerInputSchema,
  positiveIntegerInputSchema,
} from "../numericSchemas.js";

export const mediaCommerceRequestSchema = z.object({
  interaction_mode: z.string().trim().nullable().optional(),
  event_type: z.string().trim().nullable().optional(),
  chat_id: positiveIntegerInputSchema.nullable().optional(),
  scene_session_id: z.string().trim().nullable().optional(),
  active_scene_session_id: z.string().trim().nullable().optional(),
  turn_no: nonNegativeIntegerInputSchema.nullable().optional(),
  scene_turn_no: nonNegativeIntegerInputSchema.nullable().optional(),
  character_i: positiveIntegerInputSchema.nullable().optional(),
  scene_mode: z.string().trim().nullable().optional(),
  media_signature: z.string().trim().nullable().optional(),
  photo_sku: z.string().trim().min(1).nullable().optional(),
  base_price_xtr: nonNegativeIntegerInputSchema.nullable().optional(),
  should_offer: z.boolean().nullable().optional(),
  panel_message_id: positiveIntegerInputSchema.nullable().optional(),
  price_required: nonNegativeIntegerInputSchema.nullable().optional(),
  has_media_offer: z.boolean().nullable().optional(),
  token_rows_prepared: nonNegativeIntegerInputSchema.nullable().optional(),
  callback_data: z.string().trim().nullable().optional(),
  callback_query_id: z.string().trim().nullable().optional(),
  inbound_message_id: positiveIntegerInputSchema.nullable().optional(),
  panel_text: z.string().nullable().optional(),
  panel_entities_json: z.unknown().nullable().optional(),
  raw_update: z.unknown().nullable().optional(),
  invoice_payload: z.string().trim().nullable().optional(),
  pre_checkout_query_id: z.string().trim().nullable().optional(),
  telegram_payment_charge_id: z.string().trim().nullable().optional(),
  provider_payment_charge_id: z.string().trim().nullable().optional(),
  payment_source: z.enum(["stars", "sbp"]).nullable().optional(),
  payment_currency: z.string().trim().nullable().optional(),
  payment_total_amount: nonNegativeIntegerInputSchema.nullable().optional(),
  payment_token: z.string().trim().nullable().optional(),
  external_payment_id: z.string().trim().nullable().optional(),
  checkout_url: z.string().trim().nullable().optional(),
  feature_key: z.string().trim().nullable().optional(),
  invoice_link: z.string().trim().nullable().optional(),
  invoice_token: z.string().trim().nullable().optional(),
  fulfillment_invoice_token: z.string().trim().nullable().optional(),
  target_message_id: positiveIntegerInputSchema.nullable().optional(),
  current_uuid: z.string().trim().nullable().optional(),
  action_kind: z.string().trim().nullable().optional(),
  requested_action: z.string().trim().nullable().optional(),
  force_deliver_after_payment: z.boolean().nullable().optional(),
  paid_access_mode: z.string().trim().nullable().optional(),
  log_event_type: z.string().trim().nullable().optional(),
  access_mode: z.string().trim().nullable().optional(),
  log_price_xtr: nonNegativeIntegerInputSchema.nullable().optional(),
  photo_url: z.string().trim().nullable().optional(),
  selected_uuid: z.string().trim().nullable().optional(),
  caption_text: z.string().nullable().optional(),
  caption_entities_json: z.unknown().nullable().optional(),
  subscription_offer_reason: z
    .enum(["subscription_command", "daily_turn_limit"])
    .nullable()
    .optional(),
  subscription_active: z.boolean().nullable().optional(),
  scene_access_active: z.boolean().nullable().optional(),
  free_scene_unlocks: nonNegativeIntegerInputSchema.nullable().optional(),
  free_photo_unlocks: nonNegativeIntegerInputSchema.nullable().optional(),
  free_fast_scene_skips: nonNegativeIntegerInputSchema.nullable().optional(),
  turn_limit: positiveIntegerInputSchema.nullable().optional(),
  turns_today: nonNegativeIntegerInputSchema.nullable().optional(),
  turn_limit_reset_text: z.string().trim().nullable().optional(),
  idempotency_key: z.string().trim().nullable().optional(),
  offer_message_id: positiveIntegerInputSchema.nullable().optional(),
  ab_test: z.unknown().nullable().optional(),
  subscription_invoice_tokens: z
    .array(z.string().trim().min(1))
    .nullable()
    .optional(),
  source: z.string().trim().nullable().optional(),
  update_id: positiveIntegerInputSchema.nullable().optional(),
});

export type MediaCommerceDecisionRequest =
  z.infer<typeof mediaCommerceRequestSchema>;
