import type {
  MediaCommerceDecisionResponse,
  MediaCommerceRoute,
} from "../mediaCommerceTypes.js";
import type { MediaCommerceDecisionRequest } from "./requestSchema.js";
import { normalizeFeatureKey } from "./paymentFlow.js";
import {
  normalizeLowerString,
  normalizeNonNegativeInteger,
  normalizePositiveInteger,
  normalizeString,
  parseJsonArray,
} from "./utils.js";

export function buildBaseResponse(
  input: MediaCommerceDecisionRequest,
  route: MediaCommerceRoute,
): MediaCommerceDecisionResponse {
  return {
    route,
    operation: "noop",
    interaction_mode: normalizeString(input.interaction_mode),
    event_type: normalizeString(input.event_type),
    chat_id: normalizePositiveInteger(input.chat_id),
    scene_session_id: normalizeString(input.scene_session_id),
    active_scene_session_id: normalizeString(input.active_scene_session_id),
    turn_no: normalizeNonNegativeInteger(input.turn_no),
    scene_turn_no: normalizeNonNegativeInteger(input.scene_turn_no),
    character_i: normalizePositiveInteger(input.character_i),
    scene_mode: normalizeString(input.scene_mode),
    media_signature: normalizeString(input.media_signature),
    base_price_xtr: normalizePositiveInteger(input.base_price_xtr),
    price_required: normalizeNonNegativeInteger(input.price_required),
    callback_query_id: normalizeString(input.callback_query_id),
    callback_data: normalizeString(input.callback_data),
    inbound_message_id: normalizePositiveInteger(input.inbound_message_id),
    invoice_payload: normalizeString(input.invoice_payload),
    pre_checkout_query_id: normalizeString(input.pre_checkout_query_id),
    telegram_payment_charge_id: normalizeString(input.telegram_payment_charge_id),
    provider_payment_charge_id: normalizeString(input.provider_payment_charge_id),
    payment_source: input.payment_source ?? null,
    payment_currency: normalizeString(input.payment_currency),
    payment_total_amount: normalizeNonNegativeInteger(input.payment_total_amount),
    payment_token: normalizeString(input.payment_token),
    external_payment_id: normalizeString(input.external_payment_id),
    checkout_url: normalizeString(input.checkout_url),
    subscription_active: input.subscription_active === true,
    scene_access_active: input.scene_access_active === true,
    feature_key: normalizeFeatureKey(input.feature_key),
    invoice_link: normalizeString(input.invoice_link),
    invoice_token: normalizeString(input.invoice_token),
    fulfillment_invoice_token: normalizeString(input.fulfillment_invoice_token),
    target_message_id: normalizePositiveInteger(input.target_message_id),
    current_uuid: normalizeLowerString(input.current_uuid),
    log_event_type: normalizeString(input.log_event_type),
    access_mode: normalizeString(input.access_mode),
    log_price_xtr: normalizeNonNegativeInteger(input.log_price_xtr) ?? 0,
    photo_url: normalizeString(input.photo_url),
    selected_uuid: normalizeLowerString(input.selected_uuid),
    caption_text: normalizeString(input.caption_text),
    caption_entities_json: parseJsonArray(input.caption_entities_json),
    subscription_offer_reason:
      input.subscription_offer_reason ?? null,
    turn_limit: normalizePositiveInteger(input.turn_limit),
    turns_today: normalizeNonNegativeInteger(input.turns_today),
    turn_limit_reset_text: normalizeString(input.turn_limit_reset_text),
    idempotency_key: normalizeString(input.idempotency_key),
    offer_message_id: normalizePositiveInteger(input.offer_message_id),
    subscription_invoice_tokens: input.subscription_invoice_tokens ?? null,
    source: normalizeString(input.source),
    update_id: normalizePositiveInteger(input.update_id),
    panel_message_id: normalizePositiveInteger(input.panel_message_id),
    panel_text: normalizeString(input.panel_text),
    panel_entities_json: parseJsonArray(input.panel_entities_json),
  };
}
